/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cash_register.glb --draco 
Author: Prince Obrymec (https://sketchfab.com/prince-obrymec)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cash-register-e0bfaac986474b31ad9ea84290a3eb12
Title: Cash Register
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/cash_register.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.register_register_0.geometry} material={materials.register} />
          <mesh geometry={nodes.register_glass_0.geometry} material={materials.glass} />
        </group>
        <mesh geometry={nodes.drawer_register_0.geometry} material={materials.register} position={[0, 0, 18.352]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cash_register.glb')
